version: '3.8'

networks:
  grafananet:

services:
  victoriametrics:
    image: victoriametrics/victoria-metrics
    ports:
      - 9090:8428
    command:
      - "--httpListenAddr=:8428"
    networks:
      - grafananet
    restart: always

  grafana:
    image: grafana/grafana
    networks:
      - grafananet
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/


  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafananet